### ISSUE TITLE
Tozti crash without error if we forget to npm run build

### ISSUE THREAD

**Issue by poechsel** [tozti/tozti#11]
If we forget to build the core's js part then Tozti's server will fail without a verbose error message.

```
Traceback (most recent call last):
  File "/home/pierre/temp_tozti/.venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 460, in __init__
    raise ValueError('Not a directory')
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pierre/temp_tozti/tozti/__main__.py", line 246, in <module>
    main()
  File "/home/pierre/temp_tozti/tozti/__main__.py", line 210, in main
    app.router.add_static('/static/{}'.format(name), dir)
  File "/home/pierre/temp_tozti/.venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 904, in add_static
    append_version=append_version)
  File "/home/pierre/temp_tozti/.venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 463, in __init__
    "No directory exists at '{}'".format(directory)) from error
ValueError: No directory exists at '/home/pierre/temp_tozti/dist'
```

It should be easy to add a more verbose error message

**Comment by dancsi** [comment]
It seems to me that since 338f2dc481116651023815c2cc4c42783e712a28 tozti does not crash anymore, but it just gives 404 errors when trying to load the files from `dist/` that need to be built using `npm run build`

**Comment by Lapin0t** [comment]
@dancsi indeed, but it might be a good idea to check if at least every file in `includes` exists (and if `static_dir` exists).
