### ISSUE TITLE
name 'query' undefined

### ISSUE THREAD

**Issue by poechsel** [tozti/tozti#16]
When trying to add a new ressource using api_cli :
```
>>> scripts.api_cli.create_resource(type= "http://127.0.0.1:8080/static/core/types/user.json", attributes= {"name": "foo", "email": "a@a.com", "login": "bjr"})
```
Tozti's storage will put an error:
```
Traceback (most recent call last):
  File "/home/pierre/tozti/.venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/home/pierre/tozti/.venv/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/home/pierre/tozti/tozti/tozti/store/__init__.py", line 59, in resources_post
    return json_response({'data': await req.app['tozti-store'].get(id)})
  File "/home/pierre/tozti/tozti/tozti/store/engine.py", line 352, in get
    resp = await self.find_one(id)
  File "/home/pierre/tozti/tozti/tozti/store/engine.py", line 328, in find_one
    resp = await self._resources.find_one(query, {'_id': id})
NameError: name 'query' is not defined
```

https://github.com/tozti/tozti/blob/52c6a93f68cea4b18d4c63237aecea69db21c606/tozti/store/engine.py#L328

**Comment by poechsel** [comment]
Fixed in https://github.com/tozti/tozti/commit/eae13f093443ba43d97951204d6e57e9ad8f0315
